export let products = [
  {
    id: 1,
    title: "Linea GEMA",
    price: 245000,
    description: "Linea GEMA",
    img: "https://res.cloudinary.com/dx1uxwqlq/image/upload/v1719447003/terminaciones_bahia_logo_tvzalk.png",
    stock: 10,
    category: "LineaGema",
  },
  {
    id: 2,
    title: "Linea TEKNA",
    price: 285000,
    description: "Linea TEKNA",
    img: "https://res.cloudinary.com/dx1uxwqlq/image/upload/v1719447003/terminaciones_bahia_logo_tvzalk.png",
    stock: 10,
    category: "LineaTekna",
  },
  {
    id: 3,
    title: "Linea GEMA",
    price: 295000,
    description: "Linea GEMA",
    img: "https://res.cloudinary.com/dx1uxwqlq/image/upload/v1719447003/terminaciones_bahia_logo_tvzalk.png",
    stock: 10,
    category: "LineaGema",
  },
  {
    id: 4,
    title: "Linea TEKNA",
    price: 224000,
    description: "Linea TEKNA",
    img: "https://res.cloudinary.com/dx1uxwqlq/image/upload/v1719447003/terminaciones_bahia_logo_tvzalk.png",
    stock: 10,
    category: "LineaTekna",
  },
];
